<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FormIb; // Adjust the import according to your model's namespace

class FormsIbSeeder extends Seeder
{
    public function run()
    {
        $submittedForms = [
            [
                'user_id' => 9991,
                'username' => 'John Doe',
                'email' => 'john@example.com',
                'user_country' => 'Pakistan',
                'country' => 'China',
                'expected_clients' => 2,
                'services' => 'Social Media',
                'trading_volume' => 5,
                'active_clients' => 3,
                'background_options' => json_encode(['Copy Trading']),
                'selectable_options' => json_encode(['EA Provider']),
                'ib_status' => 0,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 9992,
                'username' => 'Jane Smith',
                'email' => 'jane@example.com',
                'user_country' => 'USA',
                'country' => 'Canada',
                'expected_clients' => 5,
                'services' => 'Affiliate Marketing',
                'trading_volume' => 10,
                'active_clients' => 4,
                'background_options' => json_encode(['Training Institute']),
                'selectable_options' => json_encode(['Market Analysis']),
                'ib_status' => 1,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 9993,
                'username' => 'Alice Johnson',
                'email' => 'alice@example.com',
                'user_country' => 'UK',
                'country' => 'Australia',
                'expected_clients' => 3,
                'services' => 'Copy Trading',
                'trading_volume' => 7,
                'active_clients' => 5,
                'background_options' => json_encode(['Copy Trading']),
                'selectable_options' => json_encode(['Signal Provider']),
                'ib_status' => 0,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 9994,
                'username' => 'Bob Brown',
                'email' => 'bob@example.com',
                'user_country' => 'Germany',
                'country' => 'France',
                'expected_clients' => 4,
                'services' => 'Forex Trading',
                'trading_volume' => 12,
                'active_clients' => 6,
                'background_options' => json_encode(['Training Institute']),
                'selectable_options' => json_encode(['Crypto Trading']),
                'ib_status' => 2,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 9995,
                'username' => 'Charlie Green',
                'email' => 'charlie@example.com',
                'user_country' => 'Australia',
                'country' => 'New Zealand',
                'expected_clients' => 1,
                'services' => 'Investment Advice',
                'trading_volume' => 8,
                'active_clients' => 2,
                'background_options' => json_encode(['Copy Trading']),
                'selectable_options' => json_encode(['Portfolio Management']),
                'ib_status' => 0,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 9996,
                'username' => 'Diana Prince',
                'email' => 'diana@example.com',
                'user_country' => 'Brazil',
                'country' => 'Argentina',
                'expected_clients' => 3,
                'services' => 'Wealth Management',
                'trading_volume' => 15,
                'active_clients' => 7,
                'background_options' => json_encode(['Training Institute']),
                'selectable_options' => json_encode(['Options Trading']),
                'ib_status' => 1,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 9997,
                'username' => 'Eve Adams',
                'email' => 'eve@example.com',
                'user_country' => 'India',
                'country' => 'Pakistan',
                'expected_clients' => 4,
                'services' => 'Social Media',
                'trading_volume' => 5,
                'active_clients' => 3,
                'background_options' => json_encode(['Copy Trading']),
                'selectable_options' => json_encode(['Market Analysis']),
                'ib_status' => 0,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 9998,
                'username' => 'Frank Castle',
                'email' => 'frank@example.com',
                'user_country' => 'Italy',
                'country' => 'Spain',
                'expected_clients' => 2,
                'services' => 'Real Estate',
                'trading_volume' => 6,
                'active_clients' => 2,
                'background_options' => json_encode(['Training Institute']),
                'selectable_options' => json_encode(['Investment Coaching']),
                'ib_status' => 2,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 9999,
                'username' => 'George Lucas',
                'email' => 'george@example.com',
                'user_country' => 'USA',
                'country' => 'Mexico',
                'expected_clients' => 3,
                'services' => 'Film Production',
                'trading_volume' => 7,
                'active_clients' => 5,
                'background_options' => json_encode(['Copy Trading']),
                'selectable_options' => json_encode(['Branding Strategy']),
                'ib_status' => 1,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 10000,
                'username' => 'Harriet Tubman',
                'email' => 'harriet@example.com',
                'user_country' => 'Canada',
                'country' => 'USA',
                'expected_clients' => 1,
                'services' => 'Social Services',
                'trading_volume' => 5,
                'active_clients' => 1,
                'background_options' => json_encode(['Training Institute']),
                'selectable_options' => json_encode(['Non-Profit Work']),
                'ib_status' => 0,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 10001,
                'username' => 'Ibrahim Ali',
                'email' => 'ibrahim@example.com',
                'user_country' => 'UAE',
                'country' => 'Kuwait',
                'expected_clients' => 4,
                'services' => 'Import/Export',
                'trading_volume' => 9,
                'active_clients' => 4,
                'background_options' => json_encode(['Copy Trading']),
                'selectable_options' => json_encode(['Market Research']),
                'ib_status' => 1,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 10002,
                'username' => 'Jack Sparrow',
                'email' => 'jack@example.com',
                'user_country' => 'Pirate Bay',
                'country' => 'Treasure Island',
                'expected_clients' => 2,
                'services' => 'Pirate Trading',
                'trading_volume' => 3,
                'active_clients' => 2,
                'background_options' => json_encode(['Training Institute']),
                'selectable_options' => json_encode(['Treasure Maps']),
                'ib_status' => 0,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 10003,
                'username' => 'Lara Croft',
                'email' => 'lara@example.com',
                'user_country' => 'UK',
                'country' => 'Egypt',
                'expected_clients' => 5,
                'services' => 'Archaeology',
                'trading_volume' => 6,
                'active_clients' => 3,
                'background_options' => json_encode(['Copy Trading']),
                'selectable_options' => json_encode(['Cultural Heritage']),
                'ib_status' => 1,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 10004,
                'username' => 'Bruce Wayne',
                'email' => 'bruce@example.com',
                'user_country' => 'Gotham',
                'country' => 'Metropolis',
                'expected_clients' => 1,
                'services' => 'Vigilante Services',
                'trading_volume' => 10,
                'active_clients' => 5,
                'background_options' => json_encode(['Training Institute']),
                'selectable_options' => json_encode(['Crime Fighting']),
                'ib_status' => 0,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 10005,
                'username' => 'Peter Parker',
                'email' => 'peter@example.com',
                'user_country' => 'USA',
                'country' => 'New York',
                'expected_clients' => 3,
                'services' => 'Photography',
                'trading_volume' => 8,
                'active_clients' => 4,
                'background_options' => json_encode(['Copy Trading']),
                'selectable_options' => json_encode(['Spider Photography']),
                'ib_status' => 1,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 10006,
                'username' => 'Clark Kent',
                'email' => 'clark@example.com',
                'user_country' => 'USA',
                'country' => 'Kansas',
                'expected_clients' => 2,
                'services' => 'Journalism',
                'trading_volume' => 4,
                'active_clients' => 3,
                'background_options' => json_encode(['Training Institute']),
                'selectable_options' => json_encode(['News Reporting']),
                'ib_status' => 0,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 10007,
                'username' => 'Wade Wilson',
                'email' => 'wade@example.com',
                'user_country' => 'Canada',
                'country' => 'Alberta',
                'expected_clients' => 4,
                'services' => 'Mercenary Work',
                'trading_volume' => 10,
                'active_clients' => 6,
                'background_options' => json_encode(['Copy Trading']),
                'selectable_options' => json_encode(['Deadpool Services']),
                'ib_status' => 2,
                'terms_agreement' => 1,
            ],
            [
                'user_id' => 10008,
                'username' => 'Tony Stark',
                'email' => 'tony@example.com',
                'user_country' => 'USA',
                'country' => 'California',
                'expected_clients' => 5,
                'services' => 'Engineering',
                'trading_volume' => 12,
                'active_clients' => 8,
                'background_options' => json_encode(['Training Institute']),
                'selectable_options' => json_encode(['Tech Innovations']),
                'ib_status' => 1,
                'terms_agreement' => 1,
            ],
        ];

        foreach ($submittedForms as $form) {
            FormIb::create($form);
        }
    }
}
